### ISSUE TITLE
Json parsing error on Windows machine

### ISSUE THREAD

**Issue by kwyss88** [mattyboy/istanbul-slack-notify#1]
I am trying to integrate this into our Visual Studio Team Services CI environment, but it's throwing a SyntaxError when trying to parse the git log message because the JSON doesn't return with the values enclosed in quotes on Windows machines. 

Here is the command causing the issue in **commit-info.js**: 
`let command = 'git log -1 --no-color --decorate=short --pretty=format:'${newFormat}' HEAD';`

The error is then thrown on this line when trying to parse the result of that command:
`let commitInfo = JSON.parse(stdout);`

This error is thrown because the JSON is formatted like this on Windows machines:
`{shortRevision:1e2d8ab,revision:1e2d8ab86d94be5e6492c44cec2ee57f1de1ec49,date:2 weeks ago,...}`

Instead of like this on Linux machines:
`{"shortRevision":"1e2d8ab","revision":"1e2d8ab86d94be5e6492c44cec2ee57f1de1ec49","date":"2 weeks ago",...}`

**Comment by mattyboy** [comment]
Have merged and pushed the windows fix into the latest npm package v1.0.19.
