### ISSUE TITLE
Add option to return non zero if coverage target not met

### ISSUE THREAD

**Issue by spoco2** [mattyboy/istanbul-slack-notify#4]
We're using this in a little company called HROnboard, and we'd now like to fail our builds if the coverage average is not met. This currently returns 0 no matter what, and usually this is best, but it would be excellent for it to optionally return 1 as well as printing coverage failed.

**Comment by mattyboy** [comment]
@spoco2 HROnboard you say... I feel like I might know some people that work there. This was a feature we were going to add initially, but decided to wait until our project had reached a maturity where it could cope with failing builds. 

If you'd like to fork the project and submit a pull with this feature I will gladly review and merge it in.

My thoughts are to add a `packageJson.coverage.haltOnFailure` boolean, which is defaulted to false into the mix. Then it you can override the boolean in your project's `package.json` to enforce coverage targets are met.

**Comment by spoco2** [comment]
@mattyboy Maaaaaaannnn... making me do the work myself!

Sure, I'll fork and use that as a pattern for introducing it in as an option. Expect a PR in the near future :)

**Comment by mattyboy** [comment]
@spoco2 I'll just add you to this project... if that is easier and allows you to make further changes down the track. I will hold you to an extremely high coding standard either way :P

**Comment by spoco2** [comment]
PR up for this issue: #5

**Comment by mattyboy** [comment]
Resolved by #5
